name: coffee_caller
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.0
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  json_serializable: ^6.3.1
  provider: ^6.0.3
  shared_preferences: 2.0.15
  socket_io_client: 2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/