import { SpinBox, Button, CheckBox, Slider, LineEdit, ScrollView, ListView,
    HorizontalBox, VerticalBox, GridBox, StandardButton } from "std-widgets.slint";


/*export SettingsWindow := Window {
    title: "CoffeeCaller - Settings";
    preferred-height: 400px;
    preferred-width: 600px;

    callback username_set <=> username_field.accepted;
    callback serveraddress_set <=> server_address_field.accepted;

    vbox := VerticalBox {
        HorizontalBox { 
            Text {
                text: "Username: ";
            }
            username_field := LineEdit {
                placeholder-text: "Username";
            }
        }
        HorizontalBox { 
            Text {
                text: "Server Address: ";
            }
            server_address_field := LineEdit {
                placeholder-text: "http://localhost:4200";
            }
        }
    }
}*/