name: Build
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './backend/yarn.lock'
      - name: Yarn install
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Build backend
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build